# Generated by ChatGPT

import os
import json

# Read the JSON configuration from the environment variable
model_config_json = os.environ.get("MODEL_CONFIG")
if not model_config_json:
    raise ValueError("required env var MODEL_CONFIG is not set")
model_config = json.loads(model_config_json)

# Convert the dictionary to a YAML string
yaml_str = ""
for model in model_config:
    yaml_str += "- name: " + model["name"] + "\n"
    yaml_str += "  parameters:\n"
    for key, value in model["parameters"].items():
        yaml_str += f"    {key}: {value}\n"
    yaml_str += f"  context_size: {model['context_size']}\n"
    yaml_str += f"  threads: {model['threads']}\n"
    if "stopwords" in model:
        yaml_str += "  stopwords:\n"
        for stopword in model["stopwords"]:
            yaml_str += f'  - "{stopword}"\n'
    yaml_str += "  roles:\n"
    for key, value in model["roles"].items():
        yaml_str += f'    {key}: "{value}"\n'
    yaml_str += "  template:\n"
    for key, value in model["template"].items():
        yaml_str += f"    {key}: {value}\n"

# Write the YAML string to a file
with open("/etc/config.yml", "w") as f:
    f.write(yaml_str)
